### PR TITLE
Add proxy support, improve logging for 207 responses and add nomad config examples

### PR DESCRIPTION
**Pull request by stevevillardi**
- Added in support for proxy connections along with the following parameters:

| Property | Description |
| --- | --- |
| `proxy_host` | Optional, specify the proxy server used for submitting log events. |
| `proxy_port` | Optional, specify the proxy port used for submitting log events. |
| `proxy_user` | Optional, specify the username used when connecting to the proxy host, if required. |
| `proxy_pass` | Optional, specify the password used when connecting to the proxy host, if required. |
| `proxy_use_ssl` | Optional, specify wether SSL is required for proxy server configuration. |
| `proxy_ignore_cert_errors` | Optional, sets the flags for proxy server  certification verification at beginning of SSL/TLS session. |

- Enhanced logging output for HTTP 207 Multi-Status responses

- Added in example fluentd config for nomad along with updated readme

### CODE REVIEW

**Review by siddharthck — COMMENTED** [review]
LGTM. Can we add unit tests for proxy config ?

**Comment by stevevillardi** [comment]
@siddharthck has there been any progress made on getting this approved by QA?

**Comment by Jun4bata** [comment]
Hello
I would also like to have a version that supports proxy connections, but will it be merged into master yet?

**Comment by siddharthck** [comment]
We have added proxy support with 1.0.6.

**Pull request closed without merging**
