### PR TITLE
DEV-111919 - Removed log from metadata

### PR DESCRIPTION
**Pull request by ashishkucheria**

### CODE REVIEW

**Review by siddharthck — APPROVED** [review]
LGTM

**Review by ahsan13jan — CHANGES_REQUESTED** [review]
We are excluding log metadata without any reason here in the fluentd plugin.
This fluentd plugin is used by other services as well.
And this fluentd plugin does not add `log` to the message.

The changes need to be made in 
https://github.com/logicmonitor/k8s-helm-charts/blob/master/lm-logs/templates/configmap.yaml#L69
I think that metadata filter adds the log.

**Comment by ashishkucheria** [comment]
> We are excluding log metadata without any reason here in the fluentd plugin. This fluentd plugin is used by other services as well. And this fluentd plugin does not add `log` to the message.
> 
> The changes need to be made in https://github.com/logicmonitor/k8s-helm-charts/blob/master/lm-logs/templates/configmap.yaml#L69 I think that metadata filter adds the log.

Yes the filters are added by fluentd filter plugin and there is no option provided to skip it. This additional metadata is redundant and also increases the network traffic and in terms price.

Are you saying this metadata is needed ? or should this be configurable ? or this should only be fixed by parent plugin.

**Comment by ahsan13jan** [comment]
I am saying we don't need to make any changes, in this plugin, Since the initial problem is not related to this.

We need to delete `log` key from https://github.com/logicmonitor/k8s-helm-charts/blob/master/lm-logs/templates/configmap.yaml#L69
which I think we can do it with `record_transformer`

**Pull request closed without merging**
